### ISSUE TITLE
Compilation error using hashmap example

### ISSUE THREAD

**Issue by metsuke0** [cbreeden/fxhash#1]
OS: FreeBSD 11.1-RELEASE
rust version: 1.19.0 stable and 1.21.0-nightly

https://gist.github.com/metsuke0/ed4adcaf35c399f2856f614fb141e57b

error[E0599]: no function or associated item named `new` found for type `std::collections::HashMap<_, _, std::hash::BuildHasherDefault<fxhash::FxHasher>>` in the current scope
 --> src/main.rs:5:19
  |
5 | let mut hashmap = FxHashMap::new();
  |                   ^^^^^^^^^^^^^^
error: aborting due to previous error
error: Could not compile `testing`.

**Comment by metsuke0** [comment]
I see the changes in the README:
let mut hashmap = FxHashMap::default();

That fixed it, thanks!

**Comment by cbreeden** [comment]
Sorry for taking so long!  Using ::new should work.  It's not clear why it isn't. I'll investigate tonight.

**Comment by michael-p** [comment]
`::new()` does not work for me either but `::default()` does the job. Maybe update the readme?
